Repository Shavius/test_site, pull requests merged in 2024-11, with the labels that each got.

#29 Add SECURITY.md (#24)
  .github/SECURITY.md
Labels: Project-Settings

#31 Develop to Main | Version 2.1.0
  .github/SECURITY.md
  src/ts/modules/Authorization.ts
  src/ts/modules/DataGetFromServer.ts
  src/ts/modules/DataSendToServer.ts
  src/ts/modules/FirebaseControl.ts
  src/ts/modules/Wizard.ts
  src/ts/specs/Wizard.spec.ts
Labels: Feature, Project-Settings, Release

#36 Legrendorg:develop to Develop
  README.md
Labels: Project-Settings

#37 Develop to Main
  README.md
Labels: Project-Settings

#38 Update README.md
  README.md
Labels: Project-Settings

#35 Feature/ranger add Class ranger
  src/ts/modules/Ranger.ts
  src/ts/specs/Ranger.spec.ts
Labels: Feature

#41 Release Version 2.2.0 in Develop
  .github/workflows/Release-LTBD.yml
  src/ts/main.ts
Labels: Idea, Project-Settings, Release

#43 Release/v2.2.0
  .github/workflows/Release-LTBD.yml
  src/ts/main.ts
Labels: Release

#45 Update Test-Actions.yml add TestFromEnvironments
  .github/workflows/Test-Actions.yml
Labels: Project-Settings
